background {
    monitor =
    path = ~/wallpapers/lock.png
    blur_passes = 2
}

# Main input area
input-field {
    monitor =
    size = 550, 70
    position = 0, -350
    fade_on_empty = false

    outline_thickness = 1
    inner_color = rgba(53, 54, 63, 0.07)
    outer_color = rgba(90, 222, 205, 0.63)
    
    font_color = rgba(214, 214, 214, 1)
    font_family = Minecraft Enchanting Table/SGA
    dots_text_format = abde # Filler until I can figure out how to get hyprlock to display random characters
    dots_size = 0.25
    dots_spacing = 0
}

# Time
label {
    monitor = eDP-1
    text = cmd[update:1000] echo "<span>$(date +'%H:%M')</span>"
    font_size = 500
    font_family = Angel wish
    color = rgba(146, 146, 146, 0.88)
    position = 0, 400
    halign = center
    valign = center
}
# Seconds
label {
    monitor = eDP-1
    text = cmd[update:1000] echo "<span>$(date +'%S')</span>"
    font_size = 50
    font_family = Angel wish
    color = rgba(146, 146, 146, 0.68)
    position = 620, 220
    halign = center
    valign = center
}

# Date
label {
    monitor = eDP-1
    text = cmd[update:1000] echo "<span>$(date +'%D')</span>"
    font_size = 50
    font_family = Angel wish
    color = rgba(99, 99, 99, 0.57)
    position = 0, 0
    halign = center
    valign = center
}

# Blender Render Progress Bar Widget
label {
    text = cmd[update:1] ~/.config/hypr/scripts/hyprlock_progress.py

    font_size = 12
    color = rgba(146, 146, 146, 0.88)

    halign = center
    valign = center

    position = 0, -950
}